### ISSUE TITLE
[v4] Display vertically by default

### ISSUE THREAD

**Issue by jorgemasta** [awran5/react-simple-star-rating#9] opened 2021-12-23 18:46 UTC
Thanks so much for this project!

I just installed it but the v4 is rendering the stars vertically, so it's not usable. If I install version 3.0.0 it works as expected.

**Comment by reallybeard** [comment] 2021-12-30 16:46
My theme was overriding all svgs with `display: block;` 

i'm not sure if this styling was removed or what happened but you can fix it by doing

```
svg.star-svg {
    display: inline;
}
```

**Comment by jasonpraful** [comment] 2022-02-06 15:55
Thanks for the tip @reallybeard ! I had the same issue, that comment helped. Created a new PR to fix this issue.

**Comment by IhsenBen** [comment] 2022-02-15 23:15
thx for the tip @reallybeard, I was going through the same issue without any customer theme conflict.
the issue is still up

**Comment by iiaan** [comment] 2022-04-09 05:45
i have the same problem, it appears vertically, how can i solve it?

**Comment by IhsenBen** [comment] 2022-04-09 16:16
> i have the same problem, it appears vertically, how can i solve it?

you have to modify the css class manually.
the answer is just above Ian...

**Comment by jasonpraful** [comment] 2022-04-09 16:24
This has been fixed.
https://github.com/awran5/react-simple-star-rating/pull/14

**Comment by jasonpraful** [comment] 2022-04-09 16:24
@jorgemasta or @awran5  - Can you please close this Issue :)

**Closed as completed** 2022-04-15 02:41 UTC

**Comment by Vladimir-art** [comment] 2022-11-29 14:47
The same issue with 5.1.7 version

**Comment by CascadeColin** [comment] 2023-03-22 20:03
@reallybeard's solution works if you have any CSS display setting cascading into the component.  It was `display: flex` cascading down in my case, and probably is the same for many others finding this thread.

**Comment by TechGitMaster** [comment] 2023-07-02 08:04
In my case I just added 'SVGstyle={ { 'display':'inline' } }' and it work. The version I used was 5.1.6
![image](https://github.com/awran5/react-simple-star-rating/assets/52535645/e4baf7ca-de00-4076-a2fc-3e83e1bdc59d)

**Comment by hktom** [comment] 2023-12-01 11:14
You can just add SVGstyle={{ display: "inline" }}

**Comment by arifikhsan** [comment] 2024-06-30 12:35
using tailwind is adding SVGclassName="inline"

![image](https://github.com/awran5/react-simple-star-rating/assets/32485694/46135730-1edc-4056-93f3-f6686f5bf6f6)
